language: python

python:
    - "2.7"
    - "3.4"
    - "3.5"

env:
    - DJANGO_VERSION=1.6.7 SAMPLE_PROJECT=sample_project
    - DJANGO_VERSION=1.7.7 SAMPLE_PROJECT=sample_project
    - DJANGO_VERSION=1.8.7 SAMPLE_PROJECT=sample_project
    - DJANGO_VERSION=1.9 SAMPLE_PROJECT=sample_project
    - DJANGO_VERSION=1.10 SAMPLE_PROJECT=sample_project

branches:
    only:
        - develop

matrix:
    exclude:

        -
            python: "3.4"
            env: DJANGO_VERSION=1.6.7 SAMPLE_PROJECT=sample_project

        -
            python: "3.5"
            env: DJANGO_VERSION=1.6.7 SAMPLE_PROJECT=sample_project

        -
            python: "3.5"
            env: DJANGO_VERSION=1.7.7 SAMPLE_PROJECT=sample_project

install:
    - pip install django==$DJANGO_VERSION docutils pygments

script:
    - cd $SAMPLE_PROJECT
    - python manage.py test
    - python setup.py check --metadata --restructuredtext --strict
